import Navbar from '@/components/navbars/Navbar';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import AuthContext from '@/context/AuthContext';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: 'favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={openSans.className}>
      <body className=" w-full max-w-screen-xl mx-auto">
        {/* tip) 바디 하위 페이지 및 컴포넌트에서 auth정보를 사용하기 위해 사용 */}
        <AuthContext>
          <header className=" sticky top-0 bg-white z-10 border-b">
            <Navbar />
          </header>
          <main>{children}</main>
        </AuthContext>
      </body>
    </html>
  );
}
